# Generated by Django 6.0.1 on 2026-01-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDB',
            fields=[
                ('Date', models.DateField()),
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=10)),
                ('MobileNo', models.IntegerField()),
                ('FoodName', models.CharField(max_length=12)),
                ('Amount', models.FloatField()),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
